services:
  portal_cerrado:
    environment:
      ENVIRONMENT: development
      CELERY_SCHEDULER: "0"
      ENABLE_LOCAL_SCHEDULER: "0"
  caddy:
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"

networks:
  portal_cerrado_net:
    driver: bridge
