import app
"""Initial baseline

Revision ID: 01ab4a2209c8
Revises: 
Create Date: 2026-09-18 17:09:40.256372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ab4a2209c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_trend_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('generated_at', app.contracts.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editorial_trend_signals_category'), 'editorial_trend_signals', ['category'], unique=False)
    op.create_index(op.f('ix_editorial_trend_signals_generated_at'), 'editorial_trend_signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_editorial_trend_signals_id'), 'editorial_trend_signals', ['id'], unique=False)
    op.create_index(op.f('ix_editorial_trend_signals_topic'), 'editorial_trend_signals', ['topic'], unique=False)
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_views_created_at'), 'page_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_views_id'), 'page_views', ['id'], unique=False)
    op.create_index(op.f('ix_page_views_path'), 'page_views', ['path'], unique=False)
    op.create_index(op.f('ix_page_views_session_hash'), 'page_views', ['session_hash'], unique=False)
    op.create_table('reporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('voice_profile', sa.JSON(), nullable=True),
    sa.Column('prompt_system', sa.JSON(), nullable=True),
    sa.Column('attribution', sa.String(length=200), nullable=True),
    sa.Column('articles_published', sa.Integer(), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('personality_stage', sa.String(length=20), nullable=True),
    sa.Column('birth_date', app.contracts.UTCDateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.contracts.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_reporters_id'), 'reporters', ['id'], unique=False)
    op.create_index(op.f('ix_reporters_slug'), 'reporters', ['slug'], unique=True)
    op.create_table('source_portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('rate_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('last_checked', app.contracts.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('robots_txt_url', sa.String(length=500), nullable=True),
    sa.Column('robots_txt_last_fetched', app.contracts.UTCDateTime(), nullable=True),
    sa.Column('robots_txt_allowed', sa.Boolean(), nullable=True),
    sa.Column('robots_txt_content', sa.Text(), nullable=True),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.contracts.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_source_portals_id'), 'source_portals', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('compliance_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('published_at', app.contracts.UTCDateTime(), nullable=True),
    sa.Column('scheduled_at', app.contracts.UTCDateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.Column('priority_tier', sa.String(length=20), nullable=True),
    sa.Column('is_curiosity', sa.Boolean(), nullable=True),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.contracts.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['reporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_slug'), 'news_articles', ['slug'], unique=True)
    op.create_table('scraping_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', app.contracts.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.contracts.UTCDateTime(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['source_portals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_tasks_id'), 'scraping_tasks', ['id'], unique=False)
    op.create_table('article_identities',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('publication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', app.contracts.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['reporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_logs_id'), 'publication_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_logs_id'), table_name='publication_logs')
    op.drop_table('publication_logs')
    op.drop_table('article_identities')
    op.drop_index(op.f('ix_scraping_tasks_id'), table_name='scraping_tasks')
    op.drop_table('scraping_tasks')
    op.drop_index(op.f('ix_news_articles_slug'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_source_portals_id'), table_name='source_portals')
    op.drop_table('source_portals')
    op.drop_index(op.f('ix_reporters_slug'), table_name='reporters')
    op.drop_index(op.f('ix_reporters_id'), table_name='reporters')
    op.drop_table('reporters')
    op.drop_index(op.f('ix_page_views_session_hash'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_path'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_created_at'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_editorial_trend_signals_topic'), table_name='editorial_trend_signals')
    op.drop_index(op.f('ix_editorial_trend_signals_id'), table_name='editorial_trend_signals')
    op.drop_index(op.f('ix_editorial_trend_signals_generated_at'), table_name='editorial_trend_signals')
    op.drop_index(op.f('ix_editorial_trend_signals_category'), table_name='editorial_trend_signals')
    op.drop_table('editorial_trend_signals')
    # ### end Alembic commands ###
