"""Add missing indexes to NewsArticle

Revision ID: 68251c738907
Revises: 01ab4a2209c8
Create Date: 2026-09-18 17:12:22.633408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68251c738907'
down_revision = '01ab4a2209c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_articles_category'), 'news_articles', ['category'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_status'), 'news_articles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_status'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_category'), table_name='news_articles')
    # ### end Alembic commands ###
