"""Add region to NewsArticle

Revision ID: 944b989187cf
Revises: fd2de82e095a
Create Date: 2026-09-18 20:28:48.277136

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '944b989187cf'
down_revision = 'fd2de82e095a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'news_articles',
        sa.Column('region', sa.String(length=20), nullable=False, server_default='ms'),
    )
    op.create_index(op.f('ix_news_articles_region'), 'news_articles', ['region'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_region'), table_name='news_articles')
    op.drop_column('news_articles', 'region')
    # ### end Alembic commands ###
