"""Remove PII from PageView

Revision ID: fd2de82e095a
Revises: 68251c738907
Create Date: 2026-09-18 17:15:57.967537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2de82e095a'
down_revision = '68251c738907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_views_session_hash'), table_name='page_views')
    op.drop_column('page_views', 'session_hash')
    op.drop_column('page_views', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_views', sa.Column('user_agent', sa.TEXT(), nullable=True))
    op.add_column('page_views', sa.Column('session_hash', sa.VARCHAR(length=64), nullable=True))
    op.create_index(op.f('ix_page_views_session_hash'), 'page_views', ['session_hash'], unique=False)
    # ### end Alembic commands ###
