"""Carregamento dos padrões de importância e engajamento."""


class PatternLoaderMixin:
    def _load_patterns(self):
        """Carrega padrões para classificação."""

        # ========== IMPORTÂNCIA ==========
        self.high_importance_keywords = {
            "war": 5,
            "guerra": 5,
            "conflict": 5,
            "conflito": 5,
            "invasion": 5,
            "invasão": 5,
            "sanctions": 5,
            "sanções": 5,
            "NATO": 4,
            "nuclear": 5,
            "terrorism": 5,
            "terrorismo": 5,
            "diplomatic crisis": 5,
            "crise diplomática": 5,
            "president": 3,
            "presidente": 3,
            "election": 4,
            "eleição": 4,
            "government": 3,
            "governo": 3,
            "congress": 3,
            "congresso": 3,
            "supreme court": 4,
            "suprema corte": 4,
            "BRICS": 3,
            "G7": 3,
            "G20": 3,
            "Federal Reserve": 4,
            "interest rate": 4,
            "taxa de juros": 4,
            "recession": 5,
            "recessão": 5,
            "inflation": 4,
            "inflação": 4,
            "stock market crash": 5,
            "crash": 5,
            "queda da bolsa": 5,
            "IPO": 3,
            "merger": 3,
            "fusão": 3,
            "acquisition": 3,
            "aquisição": 3,
            "GDP": 3,
            "PIB": 3,
            "unemployment": 4,
            "desemprego": 4,
            "OpenAI": 4,
            "ChatGPT": 4,
            "GPT": 4,
            "Google": 3,
            "Apple": 3,
            "Microsoft": 3,
            "Amazon": 3,
            "Meta": 3,
            "Tesla": 3,
            "Nvidia": 3,
            "breakthrough": 4,
            "descoberta": 4,
            "first ever": 4,
            "primeira vez": 4,
            "AI regulation": 4,
            "regulamentação IA": 4,
            "data breach": 4,
            "vazamento de dados": 4,
            "pandemic": 5,
            "pandemia": 5,
            "outbreak": 5,
            "surto": 5,
            "epidemic": 5,
            "epidemia": 5,
            "WHO": 3,
            "OMS": 3,
            "FDA approval": 4,
            "cancer cure": 5,
            "cura do câncer": 5,
            "vaccine": 4,
            "vacina": 4,
            "clinical trial": 3,
            "ensaio clínico": 3,
            "climate emergency": 5,
            "emergência climática": 5,
            "natural disaster": 5,
            "desastre natural": 5,
            "earthquake": 5,
            "terremoto": 5,
            "tsunami": 5,
            "hurricane": 4,
            "furacão": 4,
            "Amazon deforestation": 4,
            "desmatamento": 4,
        }

        self.low_importance_keywords = {
            "celebrity": 1,
            "celebridade": 1,
            "gossip": 1,
            "fofoca": 1,
            "lifestyle": 1,
            "estilo de vida": 1,
            "recipe": 1,
            "receita": 1,
            "horoscope": 1,
            "horóscopo": 1,
            "viral video": 1,
            "vídeo viral": 1,
            "meme": 1,
        }

        # ========== ENGAJAMENTO ==========
        self.high_engagement_keywords = {
            "scandal": 5,
            "escândalo": 5,
            "controversy": 4,
            "polêmica": 4,
            "exposed": 4,
            "exposto": 4,
            "leaked": 4,
            "vazou": 4,
            "arrested": 4,
            "preso": 4,
            "caught": 3,
            "pego": 3,
            "shocking": 4,
            "chocante": 4,
            "unbelievable": 4,
            "inacreditável": 4,
            "celebrity": 4,
            "celebridade": 4,
            "famous": 3,
            "famoso": 3,
            "death": 4,
            "morte": 4,
            "dies": 4,
            "morre": 4,
            "born": 3,
            "nasce": 3,
            "pregnant": 4,
            "grávida": 4,
            "millionaire": 4,
            "milionário": 4,
            "lottery": 4,
            "loteria": 4,
            "won": 3,
            "ganhou": 3,
            "prize": 3,
            "prêmio": 3,
            "launch": 3,
            "lançamento": 3,
            "new": 2,
            "novo": 2,
            "first": 3,
            "primeiro": 3,
            "exclusive": 4,
            "exclusivo": 4,
            "leak": 4,
            "vazamento": 4,
            "rumor": 3,
            "especulação": 3,
            "update": 2,
            "atualização": 2,
            "championship": 4,
            "campeonato": 4,
            "final": 3,
            "decisão": 3,
            "win": 3,
            "vitória": 3,
            "lose": 2,
            "derrota": 2,
            "transfer": 3,
            "transferência": 3,
            "signing": 3,
            "contratação": 3,
            "record": 3,
            "recorde": 3,
            "your money": 4,
            "seu dinheiro": 4,
            "your health": 4,
            "sua saúde": 4,
            "your job": 4,
            "seu emprego": 4,
            "you need to know": 4,
            "você precisa saber": 4,
            "alert": 3,
            "alerta": 3,
            "warning": 3,
            "aviso": 3,
        }

        self.low_engagement_keywords = {
            "report": 1,
            "relatório": 1,
            "study": 1,
            "estudo": 1,
            "analysis": 1,
            "análise": 1,
            "research": 1,
            "pesquisa": 1,
            "statistics": 1,
            "estatísticas": 1,
            "data": 1,
            "dados": 1,
            "document": 1,
            "documento": 1,
            "filing": 1,
            "processo": 1,
        }
