"""Categorias principais do classificador."""

CATEGORY_KEYWORDS = {

    "technology": [
        "bitcoin",
        "tecnologia",
        "startup",
        "app",
        "software",
        "digital",
        "inteligência artificial",
        "computador",
        "sistema",
        "rede",
        "cyber",
        "celular",
        "smartphone",
        "plataforma",
        "algoritmo",
        "dados",
        # EN keywords
        "ai",
        "artificial intelligence",
        "tech",
        "startup",
        "software",
        "cyber",
        "data",
        "digital",
        "openai",
        "chatgpt",
        "tesla",
        "silicon valley",
        "blockchain",
        "crypto",
        "robot",
    ],
    "sports": [
        "futebol",
        "esporte",
        "time",
        "campeonato",
        "jogador",
        "gol",
        "copa",
        "liga",
        "atleta",
        "olimpíada",
        "olímpica",
        "sul-americano",
        "torneio",
        "nba",
        "nfl",
        "fórmula",
        "corrida",
        "seleção",
        "caiaque",
        "kung fu",
        "maratona",
        "competição",
        "extremo",
        "esportivo",
        # EN keywords
        "football",
        "soccer",
        "sports",
        "championship",
        "tournament",
        "athlete",
        "player",
        "league",
        "nba",
        "nfl",
        "premier league",
        "cricket",
        "rugby",
        "tennis",
        "boxing",
        "ufc",
        "mma",
    ],
    "politics": [
        "governo",
        "política",
        "eleição",
        "congresso",
        "presidente",
        "senador",
        "deputado",
        "prefeito",
        "mandato",
        "câmara",
        "senado",
        "lei",
        "projeto",
        "votação",
        "campanha",
        "eleitoral",
        "eleitor",
        "candidato",
        "turnstile",
        "justiça",
        "juiz",
        "tribunal",
        "sentença",
        "júri",
        "orçamento",
        "público",
        "municipal",
        "estadual",
        # EN keywords
        "government",
        "election",
        "president",
        "congress",
        "senate",
        "parliament",
        "minister",
        "political",
        "vote",
        "democracy",
        "afv",
        "afd",
        "geopolitics",
        "trade war",
        "sanctions",
        "military",
        "war",
        "conflict",
        "refugee",
        "diplomat",
        "rubio",
        "ukraine",
        "israel",
        "gaza",
        "lebanon",
        "serbia",
        "taiwan",
        "china",
        "canada",
    ],
    "economy": [
        "economia",
        "pib",
        "inflação",
        "juros",
        "dólar",
        "mercado",
        "financeiro",
        "bolsa",
        "investimento",
        "empresa",
        "faturamento",
        "receita",
        "desemprego",
        "trabalho",
        "emprego",
        "salário",
        "crédito",
        "produtores",
        "bnDES",
        "empréstimo",
        # EN keywords
        "economy",
        "inflation",
        "gdp",
        "interest rate",
        "stock",
        "market",
        "financial",
        "trade",
        "export",
        "import",
        "recession",
        "unemployment",
        "central bank",
        "federal reserve",
        "bloomberg",
        "business",
    ],
    "health": [
        "saúde",
        "hospital",
        "médico",
        "vacina",
        "doença",
        "tratamento",
        "paciente",
        "clínica",
        "exame",
        "diagnóstico",
        "câncer",
        "sintoma",
        "medicamento",
        "cirurgia",
        "enfermagem",
        # EN keywords
        "health",
        "hospital",
        "doctor",
        "vaccine",
        "disease",
        "treatment",
        "patient",
        "medical",
        "clinic",
        "cancer",
        "diagnosis",
        "pharmaceutical",
    ],
    "security": [
        "polícia",
        "segurança",
        "crime",
        "delegacia",
        "tiroteio",
        "assassinato",
        "roubo",
        "tráfico",
        "maconha",
        "drogas",
        "apreensão",
        "prisão",
        "vitima",
        "suspeito",
        "ocorrência",
        "violência",
        "baleado",
        "baleada",
        "esfaqueado",
        "atropelado",
        "tiros",
        "balas",
        "sequestro",
        "feminicídio",
        "homicídio",
        "latrocínio",
        "sequestro",
        # EN keywords
        "police",
        "crime",
        "murder",
        "killed",
        "shot",
        "stabbed",
        "arrest",
        "prison",
        "security",
        "violence",
        "attack",
        "robbery",
        "trafficking",
        "homicide",
        "victim",
        "suspect",
    ],
    "agriculture": [
        "agronegócio",
        "fazenda",
        "campo",
        "agro",
        "soja",
        "pecuária",
        "colheita",
        "plantio",
        "rural",
        "gado",
        "safra",
        "agrícola",
        "milho",
        "boi",
        # EN keywords
        "agriculture",
        "farm",
        "crop",
        "soy",
        "cattle",
        "harvest",
        "rural",
        "agribusiness",
    ],

}
