"""Categorias complementares do classificador."""

CATEGORY_KEYWORDS = {
    "education": [
        "escola",
        "educação",
        "universidade",
        "estudante",
        "aluno",
        "professor",
        "ensino",
        "escolar",
        "aula",
        "vestibular",
        "enem",
        "faculdade",
        "educação",
        # EN keywords
        "education",
        "school",
        "university",
        "student",
        "teacher",
        "college",
        "academic",
        "curriculum",
    ],
    "culture": [
        "cultura",
        "arte",
        "música",
        "filme",
        "festival",
        "teatro",
        "exposição",
        "literatura",
        "artístico",
        "cinema",
        "show",
        "museu",
        "documentário",
        "patrimônio",
        "história",
        "milagre",
        "santo",
        # EN keywords
        "culture",
        "art",
        "music",
        "film",
        "museum",
        "theater",
        "theatre",
        "festival",
        "concert",
        "literature",
        "gallery",
    ],
    "clima": [
        "clima",
        "chuva",
        "temperatura",
        "el niño",
        "previsão",
        "sol",
        "tempo",
        "frio",
        "calor",
        "seca",
        "inundaç",
        "cheia",
        "meteorolog",
        "granizo",
        "nevoeiro",
        "tempestade",
        "estiagem",
        "nível",
        "rio",
        "enchente",
        # EN keywords
        "climate",
        "weather",
        "rain",
        "temperature",
        "storm",
        "flood",
        "drought",
        "forecast",
        "hurricane",
        "cyclone",
    ],
}
