"""Palavras-chave complementares do scanner."""

CATEGORY_KEYWORDS = {
    "education": [
        "educação",
        "universidade",
        "estudante",
        "curso",
        "concurso",
        "escola",
        "UFMS",
        "IFMS",
        "faculdade",
        "aula",
        "professor",
        "aluno",
        "vestibular",
        "ENEM",
        "prova",
        "ensino",
        "graduação",
        "pós",
        "mestrado",
        "doutorado",
        "aprendizado",
        "conhecimento",
        "bolsa",
        "estágio",
        "formatura",
        "diploma",
        "ensino fundamental",
        "ensino médio",
        "ensino superior",
        "matricul",
        "inscrição",
    ],
    "agriculture": [
        "agronegócio",
        "safra",
        "produtor rural",
        "exportação",
        "agro",
        "plantio",
        "soja",
        "milho",
        "algodão",
        "cana-de-açúcar",
        "pecuária",
        "gado",
        "boi",
        "suíno",
        "frango",
        "pesca",
        "aquicultura",
        "fronteira",
        "pantanal",
        "colheita",
        "plantação",
        "fertilizante",
        "insumo",
        "máquina agrícola",
        "agricultor",
        "lavoura",
        "rebanho",
        "bovino",
        "suinocultura",
        "avicultura",
    ],
    "entertainment": [
        "cultura",
        "evento",
        "show",
        "arte",
        "festival",
        "música",
        "teatro",
        "cinema",
        "filme",
        "série",
        "ator",
        "atriz",
        "celebridade",
        "famoso",
        "carnaval",
        "festa junina",
        "réveillon",
        "feriado",
        "turismo",
        "viagem",
        "praia",
        "hotel",
        "restaurante",
        "gastronomia",
        "parque",
        "exposição",
        "pintura",
        "espetáculo",
        "concerto",
        "banda",
        "cant",
        "artista",
    ],
    "economy": [
        "economia",
        "mercado",
        "emprego",
        "bolsa",
        "investimento",
        "crédito",
        "trabalho",
        "salário",
        "piso salarial",
        "INSS",
        "imposto",
        "taxa",
        "juro",
        "banco",
        "finança",
        "receita",
        "arrecadação",
        "balança comercial",
        "comércio",
        "indústria",
        "fábrica",
        "varejo",
        "atacado",
        "negócio",
        "empresa",
        "funcionário",
        "contratação",
        "demissão",
        "vaga",
        "BNDES",
    ],
}
