"""Shared terminology for translations generated by the editorial pipeline."""

import re


class TranslationGlossary:
    """Apply consistent Portuguese terminology to translated text."""

    TERMS = {
        "AI": "inteligência artificial", "ML": "machine learning", "startup": "startup",
        "IPO": "oferta pública inicial (IPO)", "CEO": "CEO", "layoffs": "demissões em massa",
        "Fed": "Federal Reserve (Banco Central dos EUA)", "interest rates": "taxas de juros",
        "inflation": "inflação", "GDP": "PIB", "recession": "recessão",
        "White House": "Casa Branca", "Congress": "Congresso", "NATO": "OTAN",
        "WHO": "OMS", "FDA": "FDA",
    }

    @classmethod
    def apply(cls, text: str) -> str:
        """Replace known English terms without changing unknown content."""
        result = text
        for english, portuguese in cls.TERMS.items():
            result = re.sub(re.escape(english), portuguese, result, flags=re.IGNORECASE)
        return result
