portals_us:
  nacionais:
    - name: "The New York Times"
      url: "https://www.nytimes.com"
      city: "New York"
    - name: "The Washington Post"
      url: "https://www.washingtonpost.com"
      city: "Washington D.C."
    - name: "The Wall Street Journal"
      url: "https://www.wsj.com"
      city: "Nacional"
    - name: "USA Today"
      url: "https://www.usatoday.com"
      city: "Nacional"
    - name: "Financial Times"
      url: "https://www.ft.com"
      city: "Nacional"
    - name: "New York Post"
      url: "https://nypost.com"
      city: "New York"
    - name: "NY Daily News"
      url: "https://www.nydailynews.com"
      city: "New York"
    - name: "The Huffington Post"
      url: "https://www.huffpost.com"
      city: "Nacional"

  tv_networks:
    - name: "CNN"
      url: "https://edition.cnn.com"
      city: "Nacional"
    - name: "FOX News"
      url: "https://www.foxnews.com"
      city: "Nacional"
    - name: "NBC News"
      url: "https://www.nbcnews.com"
      city: "Nacional"
    - name: "CBS News"
      url: "https://www.cbsnews.com"
      city: "Nacional"
    - name: "ABC News"
      url: "https://abcnews.go.com"
      city: "Nacional"
